### ISSUE TITLE
Questions about plant DNA methylation

### ISSUE THREAD

**Issue by LongZhao1992** [bioinfomaticsCSU/deepsignal#37]
Hi Ni Peng,
I am impressed by your deepsignal tools.
Our focus is on DNA methylation in plants, which not only including CG methylation, but also  CHH and CHG. What's more, there are little data in plants nanopore reads for training a model. Now, our strategy for data analysis is using Nanopolish for CG methylation detection and tombo **Alternative Model** for 6mA, CHG, and CHH detection. But we don't know the accuracy of the results. Are there any suggestions for this pipeline if we want to use deepsignal for methylation calling?

Best,
Zhao Long

**Comment by PengNi** [comment]
Hi @LongZhao1992 , thanks for your interests. We are actually working on our deepsignal models of three 5mC motifs in plants now, by using our in-house plants data. This work still needs months to be finished. I'll let you know once we finish the work.

Best,
Peng

**Comment by LongZhao1992** [comment]
Thank you @PengNi . How do you think about 6mA. I mean if the 6mA models trained in human or E. coli are suitable for plant analysis? Or do you have plans for 6mA models in plants?

**Comment by PengNi** [comment]
@LongZhao1992 , I think 6mA is more complex than 5mC. Because 6mA exists in so many motifs and there are no golden standard and enough training data for 6mA (like bisulfite for 5mC). We didn't get a statisfying general model for 6mA in our experiments. It needs more future work. I can't tell if the model trained by human or E.coli data is suitable for plants now.

Best,
Peng

**Comment by LongZhao1992** [comment]
OK，Peng. Thank you so much for your reply. I can close it now, and looking forward for your new models. 

Kindest Regards,
Zhao Long
