### ISSUE TITLE
The original FAST5 file looked for 6mA loci

### ISSUE THREAD

**Issue by chenchen-eng** [bioinfomaticsCSU/deepsignal#55]
Hello, teacher, I hope to find 6mA from the original FAST5 file. How should I set up my training set?

**Comment by PengNi** [comment]
Hi @chenchen-eng ,

Currently deepsignal doesn't not perform well in 6mA detection. 
So for 6mA detection, I suggest that you try `tombo` or `megalodon` from nanoporetech.

Best,
Peng

**Comment by chenchen-eng** [comment]
What I have is a fungus sample. If I look for 5mC, can I directly use your model? What should I do if I retrain?Thank you teacher

**Comment by PengNi** [comment]
@chenchen-eng , because the model provided deepsignal are trained by using human reads, retrain a model using reads of fungus sample is better way. 

To train a model, high-confidence sites should be selected (from bisulfite sequenceing maybe). You can check other related issues ( #13 , #10 , #7 , #32 and #50).

If you don't have high-confidence sites, using the provided model of deepsignal is suggested. But the best performance of 5mC detection in your sample is not guaranteed.

Best,
Peng

**Comment by chenchen-eng** [comment]
Thank you, teacher. Which model should 5mC use?

**Comment by PengNi** [comment]
@chenchen-eng , I suggest that you use the latest version of deepsignal and the  model `model.CpG.R9.4_1D.human_hx1.bn17.sn360.v0.1.7+.tar.gz`.

You can download the model from [google drive](https://drive.google.com/drive/folders/1zkK8Q1gyfviWWnXUBMcIwEDw3SocJg7P?usp=drive_open), and then uncompress it.

Best,
Peng
