### ISSUE TITLE
How to detect 6mA methylation using deepsignal? 

### ISSUE THREAD

**Issue by tianrenmao** [bioinfomaticsCSU/deepsignal#8]
Can I detect both 5mC and 6mA methylation with the model provided?

**Comment by PengNi** [comment]
Hi @tianrenmao ,

To detect 6mA, a new model must be used. One model is supposed to predict the methylation state of  one targeted motif in DeepSignal.

We didn't provide the 6mA (GATC) model used in our [published paper](https://academic.oup.com/bioinformatics/advance-article/doi/10.1093/bioinformatics/btz276/5474907), because it doesn't have a stable performance for other organisms (except the plasmid).

You can try to train a new model for 6mA by using features of a certain targeted motif.

Best, 
Peng

**Comment by SAMtoBAM** [comment]
Hello
Is the model provided in the google drive "model.GATC.R9_2D.tem.puc19.bn17.sn360.tar.gz" now suitable?
Thank you

**Comment by PengNi** [comment]
@SAMtoBAM , as the 6mA model is trained using R9 2D reads and only suitable for GATC motif, it is not suitable for any further use now.

Best,
Peng

**Comment by SAMtoBAM** [comment]
Hi @PengNi,
Will/Can you release a 6mA model now or in the future?
Thank you

**Comment by PengNi** [comment]
Hi @SAMtoBAM ,

Thanks very much for your interest. However, now we don't plan to release a DNA 6mA model, as we don't have data to train a more accurate model.

Megalodon may be a good choice to detect DNA 6mA at present.

Best,
Peng
